apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-gateway-deployment
  namespace: default
  labels:
    app: sc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sc-gateway
  template:
    metadata:
      labels:
        app: sc-gateway
    spec:
      containers:
        - name: sc-gateway
          image: tsalm/sc-gateway
          ports:
            - containerPort: 8080
          env:
            - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sc-wavefront-secret
                  key: api-token
                  optional: true
            - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
              valueFrom:
                secretKeyRef:
                  name: sc-wavefront-secret
                  key: uri
                  optional: true
