apiVersion: v1
kind: Service
metadata:
  name: sc-order-service-database-service
spec:
  selector:
    app: sc-order-service-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306