spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://${order.database.host}:3306/${order.database.name}
    username:
    password:
  application.name: sc-order-service # for config server and service-registry
  cloud:
    loadbalancer.ribbon.enabled: false
    kubernetes:
      loadbalancer.mode: SERVICE
      discovery.all-namespaces: true
      reload:
        enabled: true
        strategy: restart_context
  redis:
    host:
    password:
  rabbitmq:
    username:
    password:
    host:
order:
  exchange-name:
  shipping-exchange-name:
  products-api-url:
  database:
    host:
    name:
logging.level.org.springframework.cache: TRACE
management:
  endpoint.restart.enabled: true
  endpoints.web.exposure.include: "*"
wavefront.application.name: spring-cloud-demo-k8s
server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 20s