spring:
  application.name: sc-product-service # for config server and service-registry
  cloud:
    kubernetes:
      discovery.all-namespaces: true
      reload:
        enabled: true
        strategy: restart_context
product-service.product-names:
management:
  endpoint.restart.enabled: true
  endpoints.web.exposure.include: "*"
wavefront.application.name: spring-cloud-demo-asc
server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 20s